<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<EnableMicrosoftTestingPlatformCodeCoverage>false</EnableMicrosoftTestingPlatformCodeCoverage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Portivio.API\Portivio.API.csproj" />
    <ProjectReference Include="..\Portivio.Application\Portivio.Application.csproj" />
    <ProjectReference Include="..\Portivio.Domain\Portivio.Domain.csproj" />
    <ProjectReference Include="..\Portivio.Infrastructure\Portivio.Infrastructure.csproj" />
  </ItemGroup>

</Project>
